int16[] pose_x
int16[] pose_y
float32[] pose_theta

uint8[] ball_is_caught
uint8[] ball_is_visible
int16[] ball_pos_x_1
int16[] ball_pos_y_1
int16[] ball_pos_x_2
int16[] ball_pos_y_2
int16[] ball_pos_x_3
int16[] ball_pos_y_3

int16[] robot_condition
int16[] fsm_0
int16[] fsm_1
int16[] fsm_2

int16[] obs_pcl_x_1
int16[] obs_pcl_y_1
int16[] obs_pcl_x_2
int16[] obs_pcl_y_2
int16[] obs_pcl_x_3
int16[] obs_pcl_y_3

int16[] target_positioning_x
int16[] target_positioning_y